export const genreMap = [
  {
    tm_id: 'KnvZfZ7vAvv',
    tm_name: 'Alternative',
    spotify_genres: [
      'alternative dance',
      'alternative hip hop',
      'alternative metal',
      'alternative r&b',
      'alternative rock',
      'indie',
      'indie dance',
      'indie electronic',
      'indie folk',
      'indie jazz',
      'indie pop',
      'indie punk',
      'indie québécois',
      'indie r&b',
      'indie rock',
      'indie soul',
      'art pop',
      'art rock',
      'avant-garde',
      'experimental',
      'experimental hip hop',
      'post-disco',
      'post-grunge',
      'post-hardcore',
      'post-punk',
      'post-rock',
      'neo-psychedelic',
      'new wave',
      'cold wave',
      'darkwave',
      'queercore',
      'riot grrrl',
    ],
  },
  {
    tm_id: 'KnvZfZ7vAve',
    tm_name: 'Ballads/Romantic',
    spotify_genres: ['adult standards', 'quiet storm', 'soft pop', 'soft rock'],
  },
  {
    tm_id: 'KnvZfZ7vAvd',
    tm_name: 'Blues',
    spotify_genres: [
      'blues',
      'blues rock',
      'classic blues',
      'country blues',
      'modern blues',
      'soul blues',
      'boogie-woogie',
    ],
  },
  {
    tm_id: 'KnvZfZ7vAvA',
    tm_name: 'Chanson Francaise',
    spotify_genres: ['chanson', 'chanson québécoise', 'variété française'],
  },
  {
    tm_id: 'KnvZfZ7vAvk',
    tm_name: "Children's Music",
    spotify_genres: ["children's music", 'lullaby'],
  },
  {
    tm_id: 'KnvZfZ7vAeJ',
    tm_name: 'Classical',
    spotify_genres: [
      'classical',
      'classical piano',
      'opera',
      'orchestra',
      'chamber music',
      'baroque pop',
      'requiem',
      'gregorian chant',
      'neoclassical',
      'minimalism',
    ],
  },
  {
    tm_id: 'KnvZfZ7vAv6',
    tm_name: 'Country',
    spotify_genres: [
      'country',
      'country blues',
      'country hip hop',
      'country rock',
      'classic country',
      'traditional country',
      'acoustic country',
      'alt country',
      'americana',
      'bluegrass',
      'newgrass',
      'honky tonk',
      'outlaw country',
      'red dirt',
      'texas country',
      'cajun',
      'zydeco',
    ],
  },
  {
    tm_id: 'KnvZfZ7vAvF',
    tm_name: 'Dance/Electronic',
    spotify_genres: [
      'acid house',
      'acid techno',
      'bass house',
      'bass music',
      'bassline',
      'big beat',
      'big room',
      'breakbeat',
      'cedm',
      'chicago house',
      'chillstep',
      'chillwave',
      'dance',
      'dance pop',
      'deep house',
      'disco house',
      'funky house',
      'future house',
      'g-house',
      'hard house',
      'jazz house',
      'latin house',
      'lo-fi house',
      'melodic house',
      'progressive house',
      'slap house',
      'stutter house',
      'tech house',
      'tribal house',
      'tropical house',
      'disco',
      'italo disco',
      'nu disco',
      'downtempo',
      'drum and bass',
      'drumstep',
      'dub',
      'dub techno',
      'dubstep',
      'deathstep',
      'ebm',
      'edm',
      'edm trap',
      'electro',
      'electro house',
      'electro swing',
      'electroclash',
      'electrocumbia',
      'electronic',
      'electronica',
      'electropop',
      'eurodance',
      'europop',
      'footwork',
      'french house',
      'future bass',
      'gabber',
      'glitch',
      'hardcore',
      'hardcore techno',
      'hardstyle',
      'hi-nrg',
      'house',
      'hip house',
      'hypertechno',
      'idm',
      'industrial',
      'italo dance',
      'jungle',
      'liquid funk',
      'lo-fi beats',
      'lo-fi hip hop',
      'lounge',
      'melbourne bounce',
      'minimal techno',
      'melodic techno',
      'moombahton',
      'new rave',
      'nightcore',
      'progressive trance',
      'psytrance',
      'trance',
      'riddim',
      'synthpop',
      'synthwave',
      'techno',
      'trip hop',
      'uk funky',
      'uk garage',
      'vaporwave',
      'witch house',
    ],
  },
  {
    tm_id: 'KnvZfZ7vAva',
    tm_name: 'Folk',
    spotify_genres: [
      'folk',
      'folk metal',
      'folk pop',
      'folk punk',
      'folk québécois',
      'folk rock',
      'acoustic pop',
      'ambient folk',
      'anti-folk',
      'traditional folk',
      'singer-songwriter',
      'celtic',
      'celtic punk',
      'celtic rock',
      'traditional music',
    ],
  },
  {
    tm_id: 'KnvZfZ7vAv1',
    tm_name: 'Hip-Hop/Rap',
    spotify_genres: [
      'hip hop',
      'hip house',
      'alternative hip hop',
      'experimental hip hop',
      'boom bap',
      'chicago drill',
      'drill',
      'uk drill',
      'cloud rap',
      'crunk',
      'east coast hip hop',
      'west coast hip hop',
      'southern hip hop',
      'emo rap',
      'g-funk',
      'gangster rap',
      'grime',
      'uk grime',
      'hardcore hip hop',
      'horrorcore',
      'hyphy',
      'jazz rap',
      'old school hip hop',
      'underground hip hop',
      'rap',
      'rap metal',
      'rap québécois',
      'rap rock',
      'trap',
      'trap metal',
      'trap soul',
      'trap latino',
      'chinese hip hop',
      'desi hip hop',
      'german hip hop',
      'norwegian hip hop',
      'punjabi hip hop',
      'pinoy hip hop',
      'christian hip hop',
      'country hip hop',
      'french rap',
    ],
  },
  {
    tm_id: 'KnvZfZ7vAvJ',
    tm_name: 'Holiday',
    spotify_genres: ['christmas'],
  },
  {
    tm_id: 'KnvZfZ7vAvE',
    tm_name: 'Jazz',
    spotify_genres: [
      'jazz',
      'jazz beats',
      'jazz blues',
      'jazz funk',
      'jazz fusion',
      'acid jazz',
      'bebop',
      'big band',
      'brazilian jazz',
      'ethiopian jazz',
      'french jazz',
      'cool jazz',
      'free jazz',
      'hard bop',
      'nu jazz',
      'smooth jazz',
      'soul jazz',
      'swing music',
      'vocal jazz',
    ],
  },
  {
    tm_id: 'KnvZfZ7vAJ6',
    tm_name: 'Latin',
    spotify_genres: [
      'latin',
      'latin afrobeats',
      'latin alternative',
      'latin dance',
      'latin folk',
      'latin folklore',
      'latin indie',
      'latin jazz',
      'latin pop',
      'latin rock',
      'bachata',
      'axé',
      'bolero',
      'bossa nova',
      'cumbia',
      'dembow',
      'dembow belico',
      'mambo',
      'merengue',
      'nueva trova',
      'punta',
      'reggaeton',
      'salsa',
      'samba',
      'tejano',
      'trova',
      'urbano latino',
      'vallenato',
      'zouk',
      'música mexicana',
    ],
  },
  {
    tm_id: 'KnvZfZ7vAvI',
    tm_name: 'Medieval/Renaissance',
    spotify_genres: ['medieval'],
  },
  {
    tm_id: 'KnvZfZ7vAvt',
    tm_name: 'Metal',
    spotify_genres: [
      'metal',
      'alternative metal',
      'doom metal',
      'folk metal',
      'glam metal',
      'gothic metal',
      'groove metal',
      'heavy metal',
      'industrial metal',
      'nu metal',
      'power metal',
      'progressive metal',
      'speed metal',
      'stoner metal',
      'sludge metal',
      'symphonic metal',
      'thrash metal',
      'deathcore',
      'mathcore',
      'metalcore',
      'melodic hardcore',
      'hardcore punk',
      'grunge',
    ],
  },
  {
    tm_id: 'KnvZfZ7vAvn',
    tm_name: 'New Age',
    spotify_genres: ['new age', 'ambient', 'space music'],
  },
  {
    tm_id: 'KnvZfZ7vAvl',
    tm_name: 'Other',
    spotify_genres: [
      'anime',
      'comedy',
      'exotica',
      'musicals',
      'soundtrack',
      'spoken word',
      'noise music',
      'noise rock',
    ],
  },
  {
    tm_id: 'KnvZfZ7vAev',
    tm_name: 'Pop',
    spotify_genres: [
      'pop',
      'pop country',
      'pop punk',
      'pop québécoise',
      'pop rock',
      'pop soul',
      'pop urbaine',
      'pop worship',
      'bubblegum pop',
      'c-pop',
      'cantopop',
      'j-pop',
      'k-pop',
      'mandopop',
      'taiwanese pop',
      'p-pop',
      'dream pop',
      'hyperpop',
      'jangle pop',
      'power pop',
      'bedroom pop',
      'french pop',
      'german pop',
      'norwegian pop',
      'swedish pop',
      'malaysian pop',
      'turkish pop',
      'hindi pop',
      'tamil pop',
      'marathi pop',
      'gujarati pop',
      'pinoy pop',
      'desi pop',
      'bangla pop',
      'brazilian pop',
      'colombian pop',
    ],
  },
  {
    tm_id: 'KnvZfZ7vAee',
    tm_name: 'R&B',
    spotify_genres: [
      'r&b',
      'contemporary r&b',
      'dark r&b',
      'french r&b',
      'gospel r&b',
      'uk r&b',
      'chinese r&b',
      'afro r&b',
      'soul',
      'classic soul',
      'neo soul',
      'northern soul',
      'philly soul',
      'retro soul',
      'afro soul',
      'funk',
      'funk rock',
      'motown',
      'new jack swing',
    ],
  },
  {
    tm_id: 'KnvZfZ7vAed',
    tm_name: 'Reggae',
    spotify_genres: [
      'reggae',
      'reggae rock',
      'roots reggae',
      'spanish-language reggae',
      'dancehall',
      'lovers rock',
      'ragga',
      'rocksteady',
      'ska',
      'ska punk',
      'soca',
    ],
  },
  {
    tm_id: 'KnvZfZ7vAe7',
    tm_name: 'Religious',
    spotify_genres: [
      'christian',
      'christian alternative rock',
      'christian country',
      'christian folk',
      'christian hip hop',
      'christian pop',
      'christian rock',
      'ccm',
      'gospel',
      'african gospel',
      'southern gospel',
      'worship',
      'qawwali',
      'sufi',
    ],
  },
  {
    tm_id: 'KnvZfZ7vAeA',
    tm_name: 'Rock',
    spotify_genres: [
      'rock',
      'rock and roll',
      'rock en español',
      'rock quebecois',
      'acid rock',
      'anatolian rock',
      'arena rock',
      'garage rock',
      'stoner rock',
      'surf rock',
      'space rock',
      'southern rock',
      'roots rock',
      'progressive rock',
      'psychedelic rock',
      'noise rock',
      'mexican rock',
      'brazilian rock',
      'christian rock',
      'pinoy rock',
      'britpop',
      'classic rock',
      'glam rock',
      'gothic rock',
      'hard rock',
      'krautrock',
      'madchester',
      'math rock',
      'proto-punk',
      'punk',
      'horror punk',
      'skate punk',
      'rockabilly',
      'screamo',
      'shoegaze',
      'slowcore',
      'psychobilly',
    ],
  },
  {
    tm_id: 'KnvZfZ7vAeF',
    tm_name: 'World',
    spotify_genres: [
      'afrobeat',
      'afrobeats',
      'afropiano',
      'afropop',
      'afroswing',
      'asakaa',
      'highlife',
      'hiplife',
      'alté',
      'amapiano',
      'arabesk',
      'azonto',
      'bhangra',
      'bollywood',
      'kollywood',
      'bongo flava',
      'brega',
      'calypso',
      'candombe',
      'cha cha cha',
      'champeta',
      'chicha',
      'dansband',
      'dansktop',
      'entehno',
      'flamenco',
      'flamenco pop',
      'ghazal',
      'gnawa',
      'gufeng',
      'gujarati garba',
      'harana',
      'indorock',
      'kizomba',
      'kuduro',
      'luk thung',
      'malay',
      'manele',
      'mizrahi',
      'mpb',
      'native american music',
      'nederpop',
      'opm',
      'phleng phuea chiwit',
      'raï',
      'rumba congolaise',
      'russelåter',
      'sea shanties',
      'shatta',
      'shibuya-kei',
      'singeli',
      'visual kei',
      'yacht rock',
    ],
  },
];
