import { StyleSheet } from 'react-native';

export const eventDetailStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#121212',
  },
  scroll: {
    paddingHorizontal: 16,
    paddingVertical: 24,
  },
  centered: {
    flex: 1,
    backgroundColor: '#121212',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 16,
  },
  title: {
    fontSize: 26,
    fontWeight: 'bold',
    color: '#ffffff',
    textAlign: 'center',
    marginBottom: 12,
  },
  status: {
    alignSelf: 'flex-start',
    backgroundColor: '#00cc66',
    color: '#ffffff',
    fontWeight: 'bold',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 6,
    fontSize: 12,
    marginBottom: 16,
    alignItems: 'flex-start',
  },
  card: {
    backgroundColor: '#1f1f1f', // Lightened background for card
    borderRadius: 14,
    padding: 16,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 6,
  },
  section: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#ffffff',
    marginBottom: 6,
  },
  text: {
    color: '#cccccc',
    fontSize: 15,
    lineHeight: 22,
    marginBottom: 4,
    marginTop: 4,
  },
  bold: {
    fontWeight: 'bold',
    color: '#ffffff',
  },
  mainImage: {
    width: '100%',
    height: 200,
    borderRadius: 12,
    marginBottom: 12,
  },
  venueImage: {
    width: '100%',
    height: 100,
    borderRadius: 10,
    marginTop: 8,
  },
  artistImage: {
    width: 80,
    height: 80,
    borderRadius: 40,
    alignSelf: 'center',
    marginVertical: 10,
    borderColor: '#1e90ff',
    borderWidth: 2,
  },
  socialLinksContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: 12,
    marginTop: 12,
  },
  link: {
    color: '#1e90ff',
    fontWeight: 'bold',
    fontSize: 15,
    textDecorationLine: 'underline',
    marginBottom: 6,
  },
  ticketButton: {
    backgroundColor: '#00cc66',
    borderRadius: 10,
    paddingVertical: 12,
    paddingHorizontal: 20,
    alignItems: 'center',
    marginTop: 10,
  },
  ticketText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  seatmapContainer: {
    width: '100%',
    height: 240,
    borderRadius: 10,
    backgroundColor: '#1c1c1c',
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 12,
  },
  loadingText: {
    color: '#dddddd',
    marginTop: 12,
    fontSize: 16,
  },
  errorText: {
    color: '#ff4d4d',
    fontSize: 16,
    textAlign: 'center',
  },
});
